export const CampaignsData = [
    {
        to: '#',
        cardImage: '',
        target: '1.000.000',
        supporteds: '100.000 supporteds',
        progressValue: '10.000 $',
        progressPercentage: '46 %',
        cardTitle:
            'Give emergency aid in PalestineGive emergency aid in PalestineGive emergency aid in PalestineGive emergency aid in PalestineGive emergency aid in Palestine ',
        status: 'done',
        field: 'false',
    },
    {
        to: '#',
        cardImage: '',
        target: '',
        supporteds: '',
        progressValue: '',
        progressPercentage: '',
        cardTitle:
            'Not sure where to help?Give emergency aid in PalestineGive emergency aid in PalestineGive emergency aid in PalestineGive emergency aid in PalestineGive emergency aid in Palestine',
        status: '',
        field: 'true',
    },
    {
        to: '#',
        cardImage: '',
        target: '1.000.000',
        supporteds: '100.000 supporteds',
        progressValue: '10.000 $',
        progressPercentage: '46 %',
        cardTitle: 'Help in the Democratic Republic of the Congo',
        status: 'done',
        field: 'false',
    },
    {
        to: '#',
        cardImage: '',
        target: '1.000.000',
        supporteds: '100.000 supporteds',
        progressValue: '10.000 $',
        progressPercentage: '46 %',
        cardTitle: 'Donate emergency support in Afghanistan',
        status: '',
        field: 'false',
    },
    {
        to: '#',
        cardImage: '',
        target: '1.000.000',
        supporteds: '100.000 supporteds',
        progressValue: '10.000 $',
        progressPercentage: '46 %',
        cardTitle: 'Provide emergency food in Armenia',
        status: '',
        field: 'false',
    },
    {
        to: '#',
        cardImage: '',
        target: '1.000.000',
        supporteds: '100.000 supporteds',
        progressValue: '10.000 $',
        progressPercentage: '46 %',
        cardTitle: 'Support families in South Sudan through innovation',
        status: '',
        field: 'false',
    },
    {
        to: '#',
        cardImage: '',
        target: '1.000.000',
        supporteds: '100.000 supporteds',
        progressValue: '10.000 $',
        progressPercentage: '46 %',
        cardTitle: 'Help families in Nigeria',
        status: '',
        field: 'false',
    },
    {
        to: '#',
        cardImage: '',
        target: '1.000.000',
        supporteds: '100.000 supporteds',
        progressValue: '10.000 $',
        progressPercentage: '46 %',
        cardTitle: 'Give life-saving aid in Yemen',
        status: '',
        field: 'false',
    },
    {
        to: '#',
        cardImage: '',
        target: '1.000.000',
        supporteds: '100.000 supporteds',
        progressValue: '10.000 $',
        progressPercentage: '46 %',
        cardTitle: 'Give emergency aid in Ukraine',
        status: '',
        field: 'false',
    },
];
