export const inputCreatePartner = [
    {
        field: 'partnerName',
        lable: 'Company Name',
        placeholder: 'Maybank',
        type: 'INPUT',
        width: '50%',
    },
    {
        field: 'email',
        lable: 'Email Address',
        placeholder: 'maybank@gmail.com',
        type: 'INPUT',
        width: '50%',
    },
    // {
    //     field: 'phone',
    //     lable: 'Phone',
    //     placeholder: '123-45-678',
    //     pattern: '[0-9]{3}-[0-9]{2}-[0-9]{3}',
    //     type: 'INPUT_NUMBER',
    // },
    {
        field: 'paypalAccount',
        lable: 'Paypal Account ',
        placeholder: '****-****-****-****',
        type: 'INPUT',
        width: '50%',
    },
    {
        field: 'vnpayAccount',
        lable: 'VNPay Account',
        placeholder: '****-****-****-****',
        type: 'INPUT',
        width: '50%',
    },
    {
        field: 'description',
        lable: 'Description',
        placeholder: '',
        type: 'INPUT_AREA',
        width: '100%',
    },
    // {
    //     field: 'paypal',
    //     lable: 'Paypal',
    //     placeholder: 'Paypal email',
    //     type: 'INPUT',
    // },
    // {
    //     field: 'vnpay',
    //     lable: 'Vnpay',
    //     placeholder: 'Vnpay number',
    //     type: 'INPUT',
    // },
    // {
    //     field: 'momo',
    //     lable: 'Momo',
    //     placeholder: 'Momo number',
    //     type: 'INPUT',
    // },
    {
        field: 'urlLogo',
        lable: 'Logo image',
        placeholder: '',
        type: 'INPUT_UPLOAD',
    },
    // {
    //     field: 'logo_partner',
    //     lable: 'Logo partner',
    //     placeholder: '',
    //     type: 'INPUT_UPLOAD',
    // },
];
